name: CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B test --file pom.xml
  deliver:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package -DSkipTests=true --file pom.xml
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: book.jar
        path: ${{ github.workspace }}/target/book*.jar
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4
    - name: Deploy to heroku
      uses: AkhileshNS/heroku-deploy@v3.13.15
      with:
        heroku_api_key: ${secret.HEROKU_API_KEY}
        heroku_email: "romainsessa@gmail.com"
        heroku_app_name: "intense-bastion-19533"  
